Feature - Allow participants to register
HZ-HBO-ICT/it-conference pull request #118
Opened 2023-08-31 08:29 UTC by v-stamenova

For testing - migrate:fresh, db:seed:
- [ ] As a content mod you first have to create slots and schedule the presentations so that they become available to the user
- [ ] Register as a user and go to my programme and from there go to register for presentation
- [ ] The already full presentations will be marked in gray
- [ ] The presentations that are available are in purple - enroll by clicking on them
- [ ] The presentations that you are enrolled in are in dark gray - disenroll by clicking on them
- [ ] There are some validations in place - for enrolling: you cannot enroll in a presentation you are already enrolled in; you cannot enroll in a presentation if during the same time you have another presentation; you cannot enroll if the max participants is reached; for disenrolling: you cannot disenroll in a presentation you are not enrolled in

The design is questionable to say the least, feel free to fix it and I'm waiting for the PR with the view of the presentation so that we make the clicking of a block to just show the presentation and the enrolling/disenrolling to happen from that page

2023-09-10 19:33 UTC, v-stamenova commented
Bug: When speakers enrol for presentations it is not checked if they are not leading a lecture at that moment. Don't merge yet!

2023-09-11 14:56 UTC, TimKardol requested changes
Feedback:

- As we talked about the UI/UX needs a complete rework. I think that is already on the backlog. 
- There is no clear validation that someone enrolled. So a confirmation popup or something else should be added so that people know they enrolled for a lecture/workshop. 
- Colors: this is part of the UI/UX rework. Colors right now do not follow standards so it is confusing on what is actually happening.

2023-09-11 14:56 UTC, TimKardol commented on app/Http/Controllers/HubController.php
> +use Illuminate\Support\Facades\DB;
I think @dwaard mentioned something about not using this if possible?

2023-09-11 14:56 UTC, TimKardol commented on app/Http/Controllers/HubController.php
> +        DB::transaction(function () use ($presentation) {
I see the DB used here. I'd like @dwaard to take a look.

2023-09-11 14:56 UTC, TimKardol commented on database/seeders/ParticipantSeeder.php
>  use Illuminate\Support\Facades\DB;
Same thing here.

2023-09-11 14:56 UTC, TimKardol commented on routes/web.php
> +    Route::get('/dashboard/programme', [HubController::class, 'personalProgramme'])->name('my-programme');
When this gets merged: I have renamed the routes to 'myconference/...' in PR #149 . Keep that in mind.

2023-10-26 13:28 UTC, closed without merging