Feature - show sponsors on main page
HZ-HBO-ICT/it-conference pull request #124
Opened 2023-09-03 12:26 UTC by IGORnvk

Displayed the golden sponsor on the main banner and all sponsors in the 'sponsors' section. For logos I used random pictures for now to see how it looks. Also I altered the tests a bit so they would pass. For testing, migrate, seed and go to the home page.

2023-09-05 06:45 UTC, v-stamenova requested changes
I think the sponsors should be something closer to the design for the companies page. @TimKardol should take a look as well

2023-09-05 06:45 UTC, v-stamenova commented on routes/web.php
> +Route::get('/', [TeamsController::class, 'getSponsors'])->name('welcome');
I'd rather we have a `HomeController` or something, but I don't like the idea of the welcome page being from the teams controller.

2023-09-11 15:23 UTC, TimKardol requested changes

2023-09-13 17:57 UTC, TimKardol requested changes
Basically approval ready. Just take a look at the one comment I added

2023-09-13 17:57 UTC, TimKardol commented on resources/views/welcome.blade.php
> +                                    <img alt="{{ $sponsor->name }}" src="{{ $sponsor->logo_path }}" class="w-full h-full px-6 py-6">
Do the logos complete fill up the block or do they have 'whitespace' around them? I think its better if the boxes are the same size as the image/logo. Looks more professional.

2023-09-14 09:00 UTC, TimKardol commented
@IGORnvk Are you available tomorrow to sit down and pair program this?

2023-09-14 09:21 UTC, IGORnvk commented
> @IGORnvk Are you available tomorrow to sit down and pair program this?

Yes, I am. Sometime in the morning preferably)

2023-09-19 14:51 UTC, TimKardol approved these changes
Looks good!

2023-09-19 14:52 UTC, merged