Rework/cruds
HZ-HBO-ICT/it-conference pull request #297
Opened 2023-10-09 14:44 UTC by dwaard

- [x] Room
- [ ] Presentation
- [ ] Company
- [x] Booths
- [x] Sponsorships

2023-10-15 17:42 UTC, v-stamenova commented on app/Models/Room.php
> +    public function canBeDeleted() : Attribute
@dwaard do you think we should refactor it in policy?

2023-10-16 19:07 UTC, v-stamenova commented
I'm working on Presentation and maybe later on Company in #290. When I am done should I merge them over here instead of merging on development?

2023-10-18 22:28 UTC, v-stamenova commented
Before testing: run `sail artisan migrate` because a new table `user_invitation` is created in order to tackle the creation of users from the content moderator

For testing:

Room
- [ ] Create
- [ ] View
- [ ] Edit
- [ ] Delete (all presentations attached to it should get null for room_id and timeslot_id)

Presentation
- [ ] Create 
- [ ] View
- [ ] Edit (should be available to the speaker as well)
- [ ] Delete (check business logic & authorization; all records in `speakers` connected to it are deleted, as well as all connected records from `participants`)

Company
- [ ] Create (two types - one with email invitation, one with already existing user)
- [ ] View
- [ ] Edit (should be available to the company rep as well)
- [ ] Delete (check business logic & authorization; all presentations get deleted therefore all records in `speakers` connected to them are deleted, as well as all connected records from `participants`; all company members get the role simple role 'participant' and are disconnected by the company that gets deleted)

Booth
- [ ] Create
- [ ] View
- [ ] Edit
- [ ] Delete

Sponsorship
- [ ] Create
- [ ] View
- Edit - Not created. Is it needed? 
- [ ] Delete (the `is_sponsor_approved` and `sponsor_tier_id` are null in the `teams`

User
- [ ] Create (via invitation; test the invitation route)
- [ ] View
- Edit - Not created for the company mod, the user themselves have it (jetstream default). Is it needed? 
- [ ] Delete (depends on the role: if participant - removed all connected records in `participants` table; if not-main speaker - removed all connected records in `participants` table, removed record from `speakers`; if main speaker - removed all connected records in `participants` table, and the same things that occur when a presentation is deleted [check above]); if company rep - all things that happen when the company gets deleted + deleting the account of the company rep

2023-10-21 17:14 UTC, TimKardol commented
> - [ ] Delete (the `is_sponsor_approved` and `sponsor_tier_id` are null in the `teams`

`sponsor_tier_id` reverts to `null`, `is_sponsor_approved` however reverts to `0` which is different from `null`. This technically shouldn't be any problem.

2023-10-21 20:56 UTC, TimKardol requested changes

2023-10-21 20:56 UTC, TimKardol commented on resources/views/emails/user-invite.blade.php
Text under 'accept your invitation':

You will be registered as a participant by default. When the final program is released you can enrol in any of the presentations using your account.

As soon as your account has been created, you can request to host a presentation. When requesting a presentation make sure to enter the necessary information such as: a summary of the topic which will be shown on the website and the level of difficulty intended for the participants. There are three difficulty levels:

Beginner: No specific knowledge/skill necessary.
Intermediate: Basic level of knowlegde/skill.
Advanced: Experienced level of knowledge/skill.

2023-10-21 21:46 UTC, v-stamenova commented on resources/views/moderator/booths/show.blade.php
I don't think I actually implemented that one, my bad is it needed?

2023-10-22 10:45 UTC, TimKardol approved these changes

2023-10-22 10:46 UTC, merged