Rework/schedule management
HZ-HBO-ICT/it-conference pull request #327
Opened 2023-10-22 21:37 UTC by v-stamenova

2023-10-27 08:49 UTC, TimKardol commented
Found an Issue: when editing the first presentation (not the opening one) and changing the timeslot to a later one, it stays at the top of the list. It doesn't go to the bottom. See screenshot:
![image](https://github.com/HZ-HBO-ICT/it-conference/assets/54664131/df5e3223-b1a5-4340-884c-50559b17fffc)

2023-10-27 09:05 UTC, TimKardol commented
Issue: Found this when trying to replace a presentation that is already approved with another presentation.
![image](https://github.com/HZ-HBO-ICT/it-conference/assets/54664131/023aec6d-33df-4566-8c1d-a779bf5c1c15)

2023-10-27 09:49 UTC, TimKardol requested changes

2023-10-27 09:49 UTC, TimKardol commented on resources/views/moderator/schedule/presentations/remove-presentation-from-schedule.blade.php
> +    <p class="text-md pb-1">If you want you cannot replace the presentation, but you want it off the schedule, you can
Question: Is there a way to replace the presentation from this page? The grammar seems off.
```suggestion
    <p class="text-md pb-1">If you choose not to replace the presentation, you can just take it off the schedule.</p>
```

2023-10-27 09:49 UTC, TimKardol commented on resources/views/livewire/room-and-timeslot-selector.blade.php
> +                                                                                   participants: {{$room->max_participants}}
Indent is weird here. Could be a single line right?

2023-10-27 09:49 UTC, TimKardol commented on resources/views/livewire/room-and-timeslot-selector.blade.php
> +                                                                          )
Same here

2023-10-27 09:49 UTC, TimKardol commented on resources/views/moderator/requests/presentations.blade.php
> +                                                                                                                presentations</h3>
Weird indentation again

2023-10-27 09:49 UTC, TimKardol commented on resources/views/moderator/schedule/default-presentations/edit-default-presentation-form.blade.php
> +                meaning that all scheduled presentations would lose their scheduling and you need to reschedule them again. Do you want to proceed?') }}
```suggestion
                <h3 class="font-bold text-red-600">{{ __('WARNING: By extending the end time of the opening presentation, timeslots will overlap. If you proceed, all presentations will need to be rescheduled. Do you want to continue? ') }}
```

2023-10-27 09:49 UTC, TimKardol commented on resources/views/moderator/schedule/default-presentations/edit-default-presentation-form.blade.php
> +                meaning that all scheduled presentations would lose their scheduling and you need to reschedule them again. Do you want to proceed?') }}
```suggestion
                        <h3 class="font-bold text-red-600">{{ __('WARNING: You've moved the start time of the closing presentation to an earlier slot, causing an overlap in timeslots. To continue, all presentations will need to be rescheduled. Do you want to continue?') }}
```

2023-10-27 09:49 UTC, TimKardol commented on resources/views/moderator/schedule/default-presentations/edit.blade.php
> +                                kicking off the conference day.
```suggestion
                                Create the opening presentation. You can add more details about the opening presentation.
```

2023-10-27 09:49 UTC, TimKardol commented on resources/views/moderator/schedule/default-presentations/edit.blade.php
> +                                conference day on a high note.
```suggestion
                                Create the closing presentation. You can add more details about the closing presentation.
```

2023-10-27 09:49 UTC, TimKardol commented on resources/views/moderator/schedule/presentations/index.blade.php
> +                                                                                                                presentations</h3>
Weird indent

2023-10-27 09:49 UTC, TimKardol commented on resources/views/moderator/schedule/timeslots/add-timeslot-padding.blade.php
> +                enough time to calmly navigate through the building. The default minutes for this is 10 minutes. Would you like to change it?') }}</h3>
```suggestion
                enough time to calmly navigate through the building. The default changeover time is 10 minutes. Would you like to change it?') }}</h3>
```

2023-10-28 13:53 UTC, v-stamenova commented
> Found an Issue: when editing the first presentation (not the opening one) and changing the timeslot to a later one, it stays at the top of the list. It doesn't go to the bottom. See screenshot: ![image](https://user-images.githubusercontent.com/54664131/278589313-df5e3223-b1a5-4340-884c-50559b17fffc.png)

> Issue: Found this when trying to replace a presentation that is already approved with another presentation. ![image](https://user-images.githubusercontent.com/54664131/278594216-023aec6d-33df-4566-8c1d-a779bf5c1c15.png)

Fixed

2023-10-29 15:41 UTC, TimKardol approved these changes

2023-10-29 15:42 UTC, merged