Rework - 431 company roles and features
HZ-HBO-ICT/it-conference pull request #440
Opened 2024-06-23 11:59 UTC by v-stamenova

# Description

This branch introduces the new feature of action based roles within the companies. This would mean that once a company representative gain access to send out invitations they no longer need to specify role in advance. This means that once the new employee registers via the company email they'll get the chance to become a speaker (either request or join presentation) or booth owner (either request or join booth).

closes #431 

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## What needs to be tested

All tests would require as prerequisite a registration as company rep and approval of the company (use the new function to speed up approval process `sail artisan app:approve-last-created-company`)

- [ ] Invite people (preferably at least 4)
- [ ] Register as one of them and look around and make sure you can sign up as booth owner and as speaker
- [ ] After that request presentation
- [ ] After requesting ensure you cannot reach booth owners permissions
- [ ] Register as one of them and join as co-speaker
- [ ] After joining as co-speaker ensure you cannot reach booth owners permissions
- [ ] Register as a one of them and request a booth
- [ ] After requesting ensure you cannot reach speaker permissions
- [ ] Register as a one of them and join as booth owner
- [ ] After joining as booth owner ensure you cannot reach speaker permissions

# Checklist:

- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2024-06-24 09:59 UTC, TimKardol requested changes

2024-06-24 09:59 UTC, TimKardol commented on app/Livewire/Presentation/JoinAsSpeakerModal.php
> +    }
![image](https://github.com/HZ-HBO-ICT/it-conference/assets/54664131/223aedb8-84b6-44db-b75c-fb725fd78a03)

Don't know if this function is the cause of the error.
Clicked on the 'join as co-speaker' button, then the error occured.

2024-06-24 09:59 UTC, TimKardol commented on resources/views/components/dashboards/blocks/company-role-decider.blade.php
> +                            refer the backend of the component for more-->
![image](https://github.com/HZ-HBO-ICT/it-conference/assets/54664131/651d9fba-6147-4d0f-a667-9d0389554180)

See my other comment.

2024-07-01 11:45 UTC, TimKardol approved these changes

2024-07-01 13:45 UTC, merged

2024-07-01 13:47 UTC, dwaard requested changes
I tested as good as I could. These are my observations:

- I was able to invite users, and accept an invitation.
- When inviting, the 'Add' button might be renamed to 'Invite' or 'Send invitation'
- After sending, there is no confirmation message that the invitation is sent
- As a user who accepted an invitation, I could look around, add myself as a co-speaker, but cannot request a booth
- As any user I cannot see who the speaker(s) of a presentation are
- Another invited user was able to request a booth
- As an admin: ERROR `View [crew.details.booth] not found.`
- As an invited user, I am not able to request a presentation. It might be because there was already a presentation associated with the company
- As company rep, I do not have clear overview of which presentations and booths are associated to my company

Not sure what in this list is correct or not and if the error is part of this PR

2024-07-01 13:47 UTC, dwaard commented on resources/views/auth/registration-via-invitation.blade.php
> +                            <h2 class="text-4xl font-bold text-white drop-shadow-md text-center leading-tight">We are in
All this empty space really necessary?

2024-07-01 13:47 UTC, dwaard commented on resources/views/auth/registration-via-invitation.blade.php
> +                                                <p id="length-false" class="before:content-['✗_'] text-red-500">length
Formatting?

2024-07-01 13:47 UTC, dwaard commented on resources/views/auth/registration-via-invitation.blade.php
> +                                                    length is at
Formatting?