Rework - Programme enrollment
HZ-HBO-ICT/it-conference pull request #453
Opened 2024-07-03 14:40 UTC by IGORnvk

# Description

This pull request introduces a rework of a programme logic: enrollment/disenrollment for presentations, programme views, my programme. Mainly the connection with `Edition` was made as well as some bugfixes and refactored logic from last year. This pr is a second half of a bigger feature (the first half is in #452).

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## What needs to be tested

- [ ] Migrate fresh seed
- [ ] Log in as mod
- [ ] Fill in all the events of the edition and then activate it.
- [ ] Schedule all the existing presentations and workshops
- [ ] Change the state of the active edition to 30 in the database (since there is no way to manually change it in the application now)
- [ ] Check if the `Programme` page works
- [ ] Log in as participant
- [ ] Go to programme and enroll/disenroll for presentations
- [ ] Check if `my programme` in `my hub` works

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-07-07 15:01 UTC, v-stamenova requested changes

2024-07-07 15:01 UTC, v-stamenova commented on app/Models/Presentation.php
> +
Maybe `creator` would be a better name? Idk not mandatory to change just saying it might have better name.

2024-07-07 15:30 UTC, IGORnvk commented on resources/views/myhub/programme.blade.php
> +                            - {{Carbon::parse($presentation->end)->format('H:i')}}
Indeed it doesn't, I confused it with default presentation probably...

2024-07-08 11:27 UTC, v-stamenova approved these changes

2024-07-08 11:27 UTC, merged