Fix - Companies can request after approval
HZ-HBO-ICT/it-conference pull request #72
Opened 2023-08-12 19:09 UTC by v-stamenova

Fix of issue #44 - the companies being able to send requests even without being approved

2023-08-12 19:16 UTC, v-stamenova commented
Added also the same check in the team management, so that the company has to be approved, before the company rep is allowed to send out invitation

2023-08-18 13:55 UTC, TimKardol requested changes

2023-08-18 13:55 UTC, TimKardol commented on resources/views/teams/requests.blade.php
> +                    You currently cannot request a booth or sponsorship since your company is waiting for approval.<br>
I don't really mind the `<br>` tags, but you can change them to `<p>` or `<div>`. Or just leave them be

2023-08-18 19:45 UTC, TimKardol approved these changes
Thank you!

2023-08-18 19:46 UTC, merged