Error pages
HZ-HBO-ICT/it-conference pull request #75
Opened 2023-08-13 11:26 UTC by IGORnvk

403, 404 and 500 error pages.

2023-08-13 11:50 UTC, v-stamenova commented
You can merge with development to check how it would look like with the new font, but I'd rather have @TimKardol review it

2023-08-15 08:04 UTC, v-stamenova commented
@IGORnvk we may need 401 as well, sorry forgot about it

2023-08-16 11:13 UTC, IGORnvk commented
Done @v-stamenova

2023-08-18 14:10 UTC, TimKardol requested changes

2023-08-18 14:10 UTC, TimKardol commented on resources/views/errors/401.blade.php
> +    or ensure you've obtained the right credentials for entry.
You could link them to either registration and/or login. This way it's more helpful.

2023-08-18 14:10 UTC, TimKardol commented on resources/views/errors/401.blade.php
> +    Access Denied! This zone is exclusive to authorized attendees.<br>
Minor nitpick but change it to:
```suggestion
    Access Denied! This page is exclusive to authorized attendees.<br>
```

2023-08-18 14:10 UTC, TimKardol commented on resources/views/errors/403.blade.php
> +    Return to the <a href="/" class="text-yellow-300 hover:text-yellow-500 hover:border-b-2 hover:border-yellow-500 transition-all">main page</a> to access the open zones of knowledge and innovation.
Give the option to return to the homepage or their own dashboard if they are logged in.
I don't know the specific urls for them
```suggestion
    Return to the <a href="/dashboard" class="text-yellow-300 hover:text-yellow-500 hover:border-b-2 hover:border-yellow-500 transition-all">homepage</a> to access the whole website.
```

2023-08-18 14:10 UTC, TimKardol commented on resources/views/errors/404.blade.php
> +    Lost in the Digital Maze? You've reached a page that's on a coffee break.<br>
Have to tell the client why they are on this page.
```suggestion
    Lost in the Digital Maze? You've reached a page that does not exist.<br>
```

2023-08-18 14:10 UTC, TimKardol commented on resources/views/errors/404.blade.php
> +    Head back to the <a href="/" class="text-yellow-300 hover:text-yellow-500 hover:border-b-2 hover:border-yellow-500 transition-all">homepage</a> to explore the latest trends and sessions.
```suggestion
    Head back to the <a href="/" class="text-yellow-300 hover:text-yellow-500 hover:border-b-2 hover:border-yellow-500 transition-all">homepage</a> to explore the latest companies and speakers.
```

2023-08-26 20:11 UTC, TimKardol approved these changes

2023-08-26 20:11 UTC, merged